import ar from './locales/ar';
import so from './locales/so';

// English stays as the app's default language.
// We keep an English dictionary only for keys we explicitly translate via t('...').
const en = {
  common: {
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    somali: 'Somali',
    loading: 'Loading…',
    pleaseWait: 'Please wait…',
    errors: {
      somethingWentWrong: 'Something went wrong.',
      failedToCreate: 'Failed to create',
      failedToUpdate: 'Failed to update',
      failedToDelete: 'Failed to delete',
      failedToLoad: 'Failed to load',
      networkOrServerError: 'Network or server error',
      copyFailed: 'Copy failed',
    },

    emptyStates: {
      noData: 'No data',
      noDataFound: 'No data found',
      tryDifferentSearch: 'Try a different search.',
      notEnoughDataForChart: 'Not enough data for a chart.',
    },

    select: {
      placeholder: 'Select…',
      noOptions: 'No options.',
      noOptionsFound: 'No options found.',
      searchPlaceholder: 'Type to search…',
      typeToSearchMore: 'Type to search more…',
    },

    aria: {
      tabs: 'Tabs',
      filterSuggestedStudents: 'Filter suggested students',
    },

    filters: {
      title: 'Filters',
      resetTitle: 'Reset filters',
      academicYear: 'Academic Year',
      academicYearShort: 'AY',
      level: 'Level',
      grade: 'Grade',
      shift: 'Shift',
      section: 'Section',
      subject: 'Subject',
      cohort: 'Cohort',
      status: 'Status',
      any: 'Any',
    },

    searchPlaceholders: {
      academicYears: 'Search academic years…',
      shifts: 'Search shifts…',
      sections: 'Search sections…',
      cohorts: 'Search cohorts…',
      subjects: 'Search subjects…',
    },

    export: {
      subtitle: 'Total: {{count}} • Generated: {{date}}',
      csv: 'CSV',
      pdf: 'PDF',
      excel: 'Excel',
      pdfTitle: 'Export PDF',
      excelTitle: 'Export Excel',
      csvTitle: 'Export CSV',
      pdfFailed: 'PDF export failed',
      excelFailed: 'Excel export failed',
    },

    onlyWithStatus: '{{status}} only',
    allIncludeClosed: 'All (include closed)',
    selectDays: 'Select days',

    none: 'None',

    table: {
      order: 'Order',
      updated: 'Updated',
      actions: 'Actions',
    },
    columns: 'Columns',
    chooseColumns: 'Choose columns',
    sortBy: 'Sort by',
    previous: 'Previous',
    next: 'Next',
    rows: 'Rows',
    all: 'All',
    page: 'Page',
    of: 'of',
    showing: 'Showing',
    total: 'total',
    logout: 'Logout',
    openMenu: 'Open Menu',
    expandSidebar: 'Expand Sidebar',
    collapseSidebar: 'Collapse Sidebar',
    search: 'Search…',
    close: 'Close',

    from: 'From',
    to: 'To',

    range: {
      title: 'Range',
      today: 'Today',
      last7: 'Last 7',
      buckets: {
        day: 'Day',
        week: 'Week',
        month: 'Month',
        year: 'Year',
      },
    },

    selected: 'Selected',

    moreCount: '(+{{count}} more)',

    studentFallback: 'Student',

    retry: 'Retry',
    saving: 'Saving…',
    summary: 'Summary',
    empty: 'Empty',
    room: 'Room',
    sectionPrefix: 'Sec',

    days: {
      short: {
        sat: 'Sat',
        sun: 'Sun',
        mon: 'Mon',
        tue: 'Tue',
        wed: 'Wed',
        thu: 'Thu',
        fri: 'Fri',
      },
      long: {
        saturday: 'Saturday',
        sunday: 'Sunday',
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
      },
    },

    time: {
      am: 'AM',
      pm: 'PM',
    },

    working: 'WORKING…',

    generatedBy: 'Generated by Nuuru Al-Bayaan',

    status: {
      active: 'Active',
      inactive: 'Inactive',
      ok: 'OK',
    },

    actions: {
      add: 'Add',
      create: 'Create',
      save: 'Save',
      update: 'Update',
      edit: 'Edit',
      view: 'View',
      cancel: 'Cancel',
      clear: 'Clear',
      reset: 'Reset',
      print: 'Print',
      selectAll: 'Select All',
      preview: 'Preview',
      promote: 'Promote',
      activate: 'Activate',
      deactivate: 'Deactivate',
      reactivate: 'Reactivate',
      unlock: 'Unlock',
      remove: 'Remove',
      delete: 'Delete',
      assignments: 'Assignments',
      resetPassword: 'Reset Password',
      copy: 'Copy',
    },

    pagination: {
      pageSummary: 'Page {{page}} of {{pages}} — {{total}} total',
    },

    audit: {
      viewDetails: 'View details',
      detailsTitle: 'Audit Details',
      unknownDevice: 'Unknown device',
      localhost: 'Localhost',
      fields: 'fields',
      mobile: 'Mobile',
      unknownOs: 'Unknown OS',
      unknownBrowser: 'Unknown browser',
      labels: {
        action: 'Action',
        description: 'Description',
        ip: 'IP',
        device: 'Device',
        time: 'Time',
        raw: 'Raw',
      },

      history: {
        emptyTitle: 'No audit history.',
        emptyDescription: 'No recorded actions yet.',
      },
    },

    securityBell: {
      notificationsTitle: 'Security notifications',
      alertsTitle: 'Security alerts',
      noLockedAccounts: 'No locked accounts right now.',
      unknownUser: 'Unknown: {{username}}',
      userRoleFallback: 'USER',
      inactiveTag: 'INACTIVE',
      until: 'until {{date}}',
      attemptsLockCount: 'Attempts lock count: {{count}}',
      titles: {
        resetToDefaultAndUnlock: 'Reset password to default + unlock',
        unlockAccount: 'Unlock account (clear login lockout)',
        markActive: 'Mark account active',
        markInactive: 'Mark account inactive',
        clearNotification: 'Clear notification',
      },
      states: {
        resetting: 'Resetting…',
        unlocking: 'Unlocking…',
        activating: 'Activating…',
        inactivating: 'Inactivating…',
        clearing: 'Clearing…',
      },
      confirms: {
        markInactive: 'Mark this account as Inactive? This will log them out within seconds.',
        markActive: 'Mark this account as Active?',
      },
      toasts: {
        studentPasswordResetDefault: 'Student password reset to default',
        teacherPasswordResetDefault: 'Teacher password reset to default',
        passwordResetDefault: 'Password reset to default',
        accountUnlocked: 'Account unlocked',
        accountMarkedInactive: 'Account marked inactive',
        accountMarkedActive: 'Account marked active',
      },
      errors: {
        resetFailed: 'Reset failed',
        unlockFailed: 'Unlock failed',
        inactiveFailed: 'Inactive failed',
        activateFailed: 'Activate failed',
        clearFailed: 'Clear failed',
      },
    },
  },

  auth: {
    forcePasswordChange: {
      title: 'Change your password',
      body: {
        studentDefault: 'Your account is using the default password. For security, please set a new password.',
        userRequired: 'Your account must set a new password before continuing.',
      },
      fields: {
        newPassword: 'New password',
        confirmPassword: 'Confirm password',
      },
      placeholders: {
        newPassword: 'Enter new password',
        confirmPassword: 'Re-enter new password',
      },
      actions: {
        notNow: 'Not now',
        save: 'Save',
      },
      states: {
        saving: 'Saving…',
      },
      tooltips: {
        showPassword: 'Show password',
      },
      toasts: {
        fillBoth: 'Please fill in both fields.',
        minLength: 'Password must be at least 6 characters.',
        mismatch: 'Passwords do not match.',
        updated: 'Password updated successfully',
      },
      errors: {
        failed: 'Failed to change password.',
      },
    },
  },

  audit: {
    actions: {
      account: {
        permissionsUpdated: 'Account • Permissions Updated',
      },
    },
  },

  attendance: {
    status: {
      notMarked: 'Not marked',
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      excused: 'Excused',
      sick: 'Sick',
      medical: 'Medical',
      medicalAppointment: 'Medical appointment',
      family: 'Family',
      familyEmergency: 'Family emergency',
      other: 'Other',
    },

    marking: {
      table: {
        columns: {
          studentId: 'Student ID',
          fullName: 'Full Name',
          marked: 'Marked',
          updated: 'Updated',
          status: 'Status',
        },
        loading: 'Loading students…',
        empty: 'No students found',
      },

      moreStatusesAria: 'More statuses',
      reasonPlaceholder: 'Reason ({{max}} words max)',

      actions: {
        saveAttendance: 'Save Attendance',
      },

      footer: {
        summary: 'Present: {{present}} • Absent: {{absent}} • Late: {{late}} • Excused: {{excused}}',
        notSavedYet: 'Not saved yet',
        saved: 'Saved ({{mode}}) for {{date}}',
      },

      modes: {
        allDay: 'All day',
        perLesson: 'Per lesson',
      },

      tabs: {
        students: {
          activeNow: 'Students: Active now',
          onSelectedDate: 'Students: On selected date',
        },
        mode: {
          perLesson: 'Mode: Per lesson',
          allDay: 'Mode: All day',
        },
        date: {
          today: 'Date: Today',
          yesterday: 'Date: Yesterday',
          custom: 'Date: Custom',
        },
      },

      labels: {
        date: 'Date',
        day: 'Day',
        thisDay: 'this day',
      },

      filters: {
        period: 'Period',
      },
      searchPlaceholders: {
        periods: 'Search periods…',
      },

      periodOptions: {
        noSubject: 'No subject',
        savedPeriodLabel: 'Saved',
      },

      hints: {
        teacherLesson: 'Select Section + Subject + Period to mark attendance.',
        adminLesson: 'Select Level + Shift + Section + Subject + Period to mark attendance.',
        daily: 'Select Level + Shift + Section to mark all-day attendance.',
      },

      toasts: {
        noActiveStudentsInClass: 'No active students in this class.',
        saved: 'Attendance saved.',
        inactiveStudentsSwitchedToAsOf: 'Roster includes inactive students. Switched to “On selected date”.',
        allStudentsActiveUseCurrent: 'All students are active. You can use “Active now”.',
      },

      errors: {
        selectLessonFilters: 'Please select Section, Subject, Period, and Date.',
        selectDailyFilters: 'Please select Level, Shift, Section, and Date.',
        noPermissionEdit: 'You do not have permission to edit attendance.',
        inactiveStudentsNewNotAllowed: 'New attendance cannot be recorded while roster includes inactive students.',
        dailyAlreadyExistsNoLesson: 'Daily attendance exists for this date. Lesson attendance is blocked.',
        noActiveStudents: 'No active students found.',
        alreadySavedNoChanges: 'Already saved. No changes to save.',
        noPeriodsForSubjectToday: 'You have no periods for this subject today.',
        noLessonsInTimetable: 'No lessons exist in the timetable for this section.',
        noPeriodsScheduledForDay: 'No periods scheduled for {{day}}.',
        noSectionsForSelectedLevelShift: 'No sections found for the selected Level/Shift.',
        conflictTeacher: 'You can only edit your own attendance records.',
        conflictHasLessonSwitchToPerLesson: 'Lesson attendance exists for this date. Switch to per-lesson mode.',
        conflictHasDailySwitchToAllDay: 'All-day attendance exists for this date. Switch to all-day mode.',
        saveFailed: 'Failed to save attendance.',
        dailySavedReadOnlyTeacher: 'Attendance is already saved for this date and is read-only for teachers.',
        cannotSaveNow: 'Cannot save right now.',
      },
    },

    reports: {
      title: 'Attendance Report',

      columns: {
        date: 'Date',
        studentId: 'Student ID',
        fullName: 'Full Name',
      },

      labels: {
        range: 'Range',
        rosterCount: 'Roster count',
        student: 'Student',
        studentId: 'ID',
        markedBy: 'Marked',
        updatedBy: 'Updated',
        subject: 'Subject',
        teacher: 'Teacher',
        periodWithCode: 'Period: {{code}}',
        remarks: 'Remarks',
      },

      summaryCell: {
        counts: 'P:{{present}} A:{{absent}} L:{{late}} E:{{excused}}',
      },

      empty: {
        noAttendanceInRange: 'No attendance found for this range.',
        noRecordsInRange: 'No attendance records found for this range.',
      },

      tabs: {
        report: {
          summary: 'Report: Summary',
          details: 'Report: Details',
        },
        range: {
          today: 'Range: Today',
          last7: 'Range: Last 7 days',
          custom: 'Range: Custom',
        },
      },

      filters: {
        subjectSelectSectionFirst: 'Subject (select section first)',
        subjectLoadingPeriods: 'Subject (loading periods…)',
        subjectRequired: 'Subject (required)',
      },

      hints: {
        selectFilters: 'Select Level, Shift, and Section to view reports.',
      },

      toasts: {
        maxRangeClamped: 'Max range is 1 month. Clamped the end date.',
      },

      errors: {
        selectFilters: {
          teacher: 'Please select Section, Subject, and date range',
          admin: 'Please select Level, Shift, Section, and date range',
        },
        noPeriodsForSubject: 'No timetable periods found for this subject.',
        loadFailed: 'Failed to load report',
        detailsLoadFailed: 'Failed to load details',
      },

      actions: {
        viewStudent: 'View student',
        viewStudentAria: 'View {{name}}',
      },

      studentModal: {
        title: 'Student',
        titleWithName: 'Student • {{name}} ({{id}})',
        noStudentSelected: 'No student selected.',
      },

      export: {
        subtitleWithRoster: 'Range: {{from}} to {{to}} • Roster: {{rosterCount}}',
        subtitleRangeOnly: 'Range: {{from}} to {{to}}',
        sheet: {
          summary: 'Summary',
          details: 'Details',
        },
      },
    },
  },

  announcements: {
    page: {
      title: 'Announcements',
      loading: 'Loading announcements…',
      empty: 'No announcements yet.',
      confirmDelete: 'Are you sure you want to delete this announcement?',
      actions: {
        post: 'Post',
      },
      status: {
        posting: 'Posting…',
        updating: 'Updating…',
        deleting: 'Deleting…',
      },
      form: {
        titlePlaceholder: 'Announcement title…',
        bodyPlaceholder: 'Write your announcement details…',
        editTitlePlaceholder: 'Edit title',
      },
      meta: {
        postedBy: 'Posted by {{author}} ({{role}}) on {{date}}',
        updatedBy: 'Updated by {{updatedBy}}{{roleSuffix}}{{dateSuffix}}',
        onPrefix: 'on',
      },
      toasts: {
        fillTitleAndBody: 'Please fill out both title and body',
        posted: 'Announcement posted successfully!',
        updated: 'Announcement updated!',
        deleted: 'Announcement deleted!',
      },
    },
  },

  timetable: {
    grid: {
      noDaysSelected: 'No days selected.',
      noPeriods: 'No periods',
      break: 'Break',
      breakLocked: 'Break (locked)',
      dragToMove: 'Drag to move',
    },

    page: {
      loadingSlots: 'Loading slots…',

      table: {
        day: 'Day',
      },

      filters: {
        subject: 'Subject',
        days: 'Days',
      },

      actions: {
        downloadCsv: 'Download CSV',
        addSlot: 'Add Slot',
        addSlotsDays: 'Add Slots (Days)',
        swap: 'Swap',
        move: 'Move',
      },

      states: {
        adding: 'Adding…',
      },

      swapModal: {
        title: 'Choose Action',
      },

      print: {
        selectSection: 'Select Section',
      },

      confirms: {
        deleteSlot: 'Delete this slot?',
      },

      toasts: {
        slotMoved: 'Slot moved',
        slotsSwapped: 'Slots swapped',
        slotCreated: 'Slot created',
        slotsCreated: 'Slots created',
        deleted: 'Deleted',
      },

      errors: {
        teacherViewOnly: 'Teachers can only view timetable',
        noEditPermission: 'You do not have permission to edit timetable',
        noAddPermission: 'You do not have permission to add timetable slots',
        noDeletePermission: 'You do not have permission to delete timetable slots',
        noPrintPermission: 'You do not have permission to print timetable',
        noDownloadPermission: 'You do not have permission to download timetable',

        fillRequiredFields: 'Fill required fields',
        selectExactlyOneDayForAddSlot: 'Select exactly one day for Add Slot',

        breakCannotBeMoved: 'Break cannot be moved',
        cannotDropOnBreak: 'Cannot drop onto a Break',
        breakCannotBeSwapped: 'Break cannot be swapped',
        moveNotAllowedOnOccupiedCell: 'Move is not allowed on an occupied cell.',

        loadFailed: 'Failed to load timetable',
        loadTodayFailed: 'Failed to load today schedule',

        moveFailed: 'Move failed',
        swapFailed: 'Swap failed',
        createFailed: 'Failed to create',
        createBulkFailed: 'Failed to create bulk',
        deleteFailed: 'Delete failed',

        selectSection: 'Select a section',
        noSlotsToExport: 'No slots to export',

        someDaysFailed: 'Some days failed: {{details}}{{moreSuffix}}',
        moreSuffix: ' (+{{count}} more)',
      },

      empty: {
        setValidTimeRange: 'Set a valid time range to show periods.',
      },

      conflicts: {
        classConflict: 'Class conflict',
        teacherConflict: 'Teacher conflict',
        roomConflict: 'Room conflict',
        invalidDay: 'Invalid day',
        conflict: 'Conflict',
      },

      export: {
        filename: 'timetable.csv',
        headers: {
          day: 'Day',
          start: 'Start',
          end: 'End',
          type: 'Type',
          subject: 'Subject',
          teacher: 'Teacher',
          room: 'Room',
        },
        type: {
          break: 'Break',
          class: 'Class',
        },
      },
    },
  },
  nav: {
    dashboard: 'Dashboard',
    finance: 'Finance',
    financeDashboard: 'Dashboard',
    financeAccounts: 'Accounts',
    financeStudentFinance: 'Student Finance',
    financePayroll: 'Payroll',
    financeExpenses: 'Expenses',
    myClasses: 'My Classes',
    profile: 'Profile',
    people: 'Users',
    students: 'Students',
    teachers: 'Teachers',
    userManagement: 'User Management',
    academics: 'Academics',
    classes: 'Classes',
    subjects: 'Subjects',
    cohorts: 'Cohorts',
    promotions: 'Promotions',
    transfers: 'Transfers',
    setup: 'Setup',
    grades: 'Grades',
    shifts: 'Shifts',
    academicYears: 'Academic Years',
    exams: 'Exams',
    examScores: 'Exam Scores',
    examSettings: 'Exam Settings',
    results: 'Results',
    transcripts: 'Transcripts',
    operations: 'Operations',
    attendance: 'Attendance',
    attendanceReports: 'Attendance Reports',
    timetable: 'Timetable',
    transcript: 'Transcript',
    library: 'Library',
    enrollments: 'Enrollments',
    announcements: 'Announcements',
  },

  finance: {
    expenses: {
      apiErrors: {
        FIN_EXPENSE_LOCKED_PAYROLL: "Payroll-generated expenses can't be edited/deleted from Expenses",
      },
    },

    studentFinance: {
      tabs: {
        receipt: 'Receipt',
        previousBalance: 'Previous Balance',
        amountType: 'Amount Type',
        feeType: 'Fee Type',
      },

      paymentModal: {
        title: 'Student Finance',
        tabs: {
          ledger: 'Ledger',
          history: 'History',
        },
        controls: {
          selectLedgerAccount: 'Select Ledger Account',
          paymentMode: 'Payment Mode',
          byLevel: 'By Level',
          byReceipt: 'By Receipt',
          paymentDate: 'Payment Date',
        },
        labels: {
          total: 'Total',
        },
        hormaris: {
          selectMonths: 'Select Hormaris Months',
        },
        actions: {
          paySelected: 'Pay Selected',
          save: 'Save',
          print: 'Print',
        },
        placeholders: {
          chooseAccount: '-- Choose Account --',
          phoneRef: 'Phone/Ref',
          defaultPhone: 'Default: {{phone}}',
          full: 'FULL',
          amountZero: '0.00',
        },
        columns: {
          no: 'No',
          month: 'Month',
          phoneRef: 'Phone/Ref',
          description: 'Description',
          drFees: 'Dr (Fees)',
          crPaid: 'Cr (Paid)',
          discount: 'Discount',
          payAmount: 'Pay Amount',
          actions: 'Actions',
          balance: 'Balance',
        },
        loading: {
          analysing: 'Analysing...',
        },
        empty: {
          noRecords: 'No records found.',
        },
        invoice: {
          titleFallback: 'Tuition Fee',
        },
        history: {
          title: 'Payment History & Receipts',
          actions: {
            printAll: 'Print All History',
            revert: 'Revert',
          },
          status: {
            cleared: 'Cleared',
          },
          descFallback: 'Standard Tuition',
          labels: {
            totalPaid: 'Total Paid',
          },
        },
        errors: {
          cannotPrintNoPayment: 'Cannot print: no payment recorded',
        },
        confirms: {
          revertMonth: 'This will REVERT payments for this month. Continue?',
        },
        validation: {
          selectAccount: 'Please select an account',
          selectAccountShort: 'Select account',
          enterValidAmount: 'Enter a valid amount',
          phoneRefRequired: 'Phone/Ref is required',
          selectHormarisMonths: 'Select Hormaris months',
          invalidAmountForMonth: 'Invalid amount for {{month}}',
          amountExceedsBalanceForMonth: 'Amount exceeds balance for {{month}}',
        },
        toasts: {
          noPaymentGroupsToRevert: 'No payment groups found to revert',
          revertingPayments: 'Reverting payments...',
          paymentsReverted: 'Payments reverted',
          failedRevertPayments: 'Failed to revert payments',
          paymentRecorded: 'Payment recorded',
          paymentFailed: 'Payment failed',
          processingHormaris: 'Processing Hormaris payment...',
          hormarisRecorded: 'Hormaris payment recorded',
          hormarisFailed: 'Hormaris payment failed',
          preparingStatement: 'Preparing statement...',
          printFailed: 'Print failed',
        },
      },

      receiptTab: {
        toasts: {
          searchFailed: 'Search failed',
          exporting: 'Exporting to Excel…',
        },
        placeholders: {
          search: 'Search ID, Name or Phone…',
        },
        filters: {
          byClassLevel: 'By Class Level',
          thisMonth: {
            title: 'Filter (This Month)',
            charged: 'Charged This Month',
            paid: 'Paid This Month',
            unpaid: 'Unpaid This Month',
            uncharged: 'Not Charged This Month',
            hormaris: 'Hormaris',
          },
        },
        actions: {
          charge: 'Charge',
          updateCharge: 'Update Charge',
          deleteCharge: 'Delete Charge',
          printMonthly: 'Monthly',
          printDaily: 'Daily',
          printPasscard: 'Passcard',
          excelExport: 'Excel Export',
          go: 'Go',
          viewInfo: 'View Info',
        },
        labels: {
          hormaris: 'Hormaris',
        },
        loading: {
          syncingLedger: 'Syncing Ledger…',
        },
        empty: {
          title: 'No records found for this selection.',
        },
        columns: {
          id: 'ID',
          studentName: 'Student Name',
          contact: 'Contact',
          class: 'Class',
          balance: 'Balance',
          info: 'Info',
        },
      },

      editTab: {
        toasts: {
          fetchFailed: 'Failed to fetch student records',
        },
        placeholders: {
          search: 'Search Student ID, Name or Phone…',
        },
        filters: {
          byClassLevel: 'By Class Level',
        },
        actions: {
          go: 'Go',
          viewInfo: 'View Info',
        },
        labels: {
          regPrefix: 'Reg:',
        },
        columns: {
          id: 'ID',
          studentName: 'Student Name',
          contact: 'Contact',
          class: 'Class',
          balance: 'Balance',
          info: 'Info',
        },
        loading: {
          fetchingProfiles: 'Fetching Profiles…',
        },
        empty: {
          title: 'No records found',
          description: 'No records found for this selection.',
        },
      },

      printTab: {
        toasts: {
          fetchFailed: 'Failed to fetch students for this class',
          selectAtLeastOne: 'Select at least one student',
        },
        title: 'Finance Reporting Hub',
        subtitle: 'Bulk Invoice & Audit Processing',
        labels: {
          selectClass: 'Select Academic Tier / Class',
          classCensus: 'Class Census:',
          studentsCountSuffix: 'Students',
        },
        placeholders: {
          targetClassLevel: 'Target Class Level',
        },
        actions: {
          fetchRegister: 'Fetch Register',
          monthlyInvoices: 'Monthly Invoices',
          dailyAuditLedger: 'Daily Audit Ledger',
          enrollmentPasscards: 'Enrollment Passcards',
        },
        loading: {
          streamingRegistry: 'Streaming Registry Data…',
        },
        columns: {
          selection: 'Selection',
          studentId: 'Student ID',
          fullName: 'Full Name',
          balanceStatus: 'Balance Status',
        },
        empty: {
          title: 'Target a class to begin reporting.',
        },
        sections: {
          reportTools: 'Report Generation Tools',
          printQueueAdvice: 'Print Queue Advice',
        },
        hints: {
          bulkPrinting:
            'Bulk printing multiple invoices may take up to 30 seconds to render high-resolution institutional watermarks.',
        },
      },
    },
  },

  modules: {
    students: 'Students',
    teachers: 'Teachers',
    transfers: 'Transfers',
    security: 'Bell Notification',
    timetable: 'Timetable',
    attendance: 'Attendance',
    attendanceReports: 'Attendance Reports',
    announcements: 'Announcements',
    cohorts: 'Cohorts',
    promotions: 'Promotions',
    transcript: 'Transcript',
    subjects: 'Subjects',
    grades: 'Grades',
    exams: 'Exams',
    results: 'Results',
  },

  perms: {
    full: 'Full Access (Select All)',
    view: 'View',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    resetPassword: 'Reset Password',
    transfer: 'Transfer',
    deactivate: 'Deactivate',
    reactivate: 'Reactivate',
    download: 'Download',
    assign: 'Assignments',
    unlock: 'Unlock',
    activate: 'Activate',
    print: 'Print',
    preview: 'Preview',
    promote: 'Promote',
    input: 'Input',
  },

  setup: {
    table: {
      emptyTitle: 'No {{title}}',
      emptyDescription: 'Create your first {{title}} to get started.',
      emptyAction: 'Add {{title}}',
    },
    grades: {
      form: {
        validation: {
          gradeNameRequired: 'Grade name is required',
          orderInvalid: 'Order must be an integer (1..N)',
        },
        labels: {
          gradeName: 'Grade name',
        },
        placeholders: {
          gradeName: 'e.g. Level 1 / Fasalka 1',
          order: '1',
        },
        hints: {
          order: 'Used by Promotions (language-agnostic). Terminal grade is the highest order.',
        },
      },
      columns: {
        grade: 'Grade',
      },
      searchPlaceholder: 'Search grades...',
      loading: 'Loading grades...',
      emptyTitle: 'No grades found',
      emptyCreateFirst: 'Create your first grade.',
      sheetName: 'Grades',
      actions: {
        add: 'Add Grade',
      },
      modal: {
        addTitle: 'Add Grade',
        editTitle: 'Edit Grade',
      },
      rowActions: {
        editTitle: 'Edit grade',
        deleteTitle: 'Delete grade',
      },
      confirms: {
        delete: 'Delete this grade? This is only allowed if not in use.',
      },
      toasts: {
        created: 'Grade created',
        updated: 'Grade updated',
        deleted: 'Grade deleted',
      },
      errors: {
        cannotDeleteInUse: 'Cannot delete: Grade is in use{{suffix}}',
      },
      refs: {
        gradeSections: 'Grade Sections',
        enrollments: 'Enrollments',
        subjects: 'Subjects',
      },
    },

    shifts: {
      form: {
        validation: {
          shiftNameRequired: 'Shift name is required',
        },
        labels: {
          shiftName: 'Shift name',
        },
        placeholders: {
          shiftName: 'e.g. Morning / Evening',
        },
      },
      columns: {
        shift: 'Shift',
      },
      searchPlaceholder: 'Search shifts...',
      loading: 'Loading shifts...',
      emptyTitle: 'No shifts found',
      emptyCreateFirst: 'Create your first shift.',
      sheetName: 'Shifts',
      actions: {
        add: 'Add Shift',
      },
      modal: {
        addTitle: 'Add Shift',
        editTitle: 'Edit Shift',
      },
      rowActions: {
        editTitle: 'Edit shift',
        deleteTitle: 'Delete shift',
      },
      confirms: {
        delete: 'Delete this shift? This is only allowed if not in use.',
      },
      toasts: {
        created: 'Shift created',
        updated: 'Shift updated',
        deleted: 'Shift deleted',
      },
      errors: {
        cannotDeleteInUse: 'Cannot delete: Shift is in use{{suffix}}',
      },
      refs: {
        gradeSections: 'Grade Sections',
        enrollments: 'Enrollments',
      },
    },

    academicYears: {
      form: {
        validation: {
          yearNameRequired: 'Academic year name is required',
        },
        labels: {
          yearName: 'Academic year',
        },
        hints: {
          yearName: 'Example: 2025/2026 (promotion year-end may auto-create if missing)',
        },
        placeholders: {
          yearName: '2025/2026',
        },
      },
      columns: {
        academicYear: 'Academic Year',
      },
      searchPlaceholder: 'Search academic years...',
      loading: 'Loading academic years...',
      emptyTitle: 'No academic years found',
      emptyCreateFirst: 'Create your first academic year.',
      sheetName: 'Academic Years',
      actions: {
        add: 'Add Academic Year',
      },
      modal: {
        addTitle: 'Add Academic Year',
        editTitle: 'Edit Academic Year',
      },
      rowActions: {
        editTitle: 'Edit academic year',
        deleteTitle: 'Delete academic year',
      },
      confirms: {
        delete: 'Delete this academic year? This is only allowed if not in use.',
      },
      toasts: {
        created: 'Academic year created',
        updated: 'Academic year updated',
        deleted: 'Academic year deleted',
      },
      errors: {
        cannotDeleteInUse: 'Cannot delete: Academic year is in use{{suffix}}',
      },
      refs: {
        enrollments: 'Enrollments',
        exams: 'Exams',
        lessonPlans: 'Lesson Plans',
        cohorts: 'Cohorts',
        teachers: 'Teachers',
      },
    },
  },

  gradeSections: {
    searchPlaceholder: 'Search grade or section...',
    actions: {
      add: 'Add Grade Section',
    },
    modal: {
      addTitle: 'Add Grade Section',
      editTitle: 'Edit Grade Section',
    },
    permissions: {
      noAdd: 'You do not have permission to add grade sections',
      noEdit: 'You do not have permission to edit grade sections',
      noViewPrint: 'You do not have permission to view/print grade sections',
      noDelete: 'You do not have permission to delete grade sections',
    },
    confirms: {
      delete: 'Are you sure you want to delete this section?',
    },
    toasts: {
      deleted: 'Deleted successfully',
    },
    columns: {
      subjects: 'Subjects',
      capacity: 'Capacity',
    },
    export: {
      title: 'Grade Sections',
      sheetName: 'Grade Sections',
    },
    table: {
      loading: 'Loading...',
      emptyTitle: 'No grade sections found',
      emptyDescription: 'Try adjusting filters or create a new one.',
    },
    rowActions: {
      viewStudentsTitle: 'View Students',
    },
    select: {
      noClassesForShift: 'No classes (sections) found for the selected shift.',
    },
    roster: {
      loading: 'Loading students...',
      emptyTitle: 'No students in this section',
      emptyDescription: 'No active students found for this grade section.',
      columns: {
        studentId: 'Student ID',
        fullName: 'Full Name',
        gender: 'Gender',
      },
      export: {
        title: 'Students Roster',
        sheetName: 'Roster',
      },
      toasts: {
        noActiveStudents: 'No active students found for this Grade Section.',
      },
      errors: {
        timeout: 'Loading students timed out. Please try again.',
      },
    },
    form: {
      labels: {
        subjects: 'Subjects',
        capacity: 'Capacity',
      },
      placeholders: {
        section: 'e.g. 1, 2, A, B',
      },
      subjects: {
        refreshTitle: 'Refresh subjects for this grade',
        noneForGrade: 'No subjects for this grade.',
        hasScores: 'has scores',
        help: 'Tick subjects to include. Subjects with existing scores cannot be removed.',
      },
      errors: {
        requiredFields: 'Please fill all required fields',
        updateBlocked: 'Update blocked: {{error}}. ({{blocked}})',
        cannotRemoveWithScores: 'Cannot remove subjects with scores: {{items}}',
        operationFailed: 'Operation failed',
      },
      toasts: {
        subjectsCleared: 'Previous subjects cleared (grade changed)',
        removedSubjectsTitle: 'Removed subjects:',
        updated: 'Updated',
        created: 'Created',
      },
      states: {
        resyncing: 'Resyncing...',
        updating: 'Updating...',
      },
      changeGradeConfirm: {
        title: 'Change Grade?',
        body: 'If you change the grade, all previously selected subjects will be cleared. Are you sure?',
        confirm: 'Yes, change',
      },
    },
  },

  subjects: {
    searchPlaceholder: 'Search subjects by name or code...',
    permissions: {
      noAdd: 'You do not have permission to add subjects',
      noEdit: 'You do not have permission to edit subjects',
      noDelete: 'You do not have permission to delete subjects',
      noExport: 'You do not have permission to export/print subjects',
    },
    confirms: {
      delete: 'Are you sure you want to delete this subject?',
    },
    errors: {
      failedToLoadGrades: 'Failed to load grades',
      subjectCodeExists: 'Subject code already exists. Please choose another.',
      cannotDeleteInUse: 'Cannot delete: Subject is used by {{count}} grade(s).',
    },
    toasts: {
      created: 'Subject created',
      updated: 'Subject updated',
      deleted: 'Subject deleted',
    },
    actions: {
      addNew: 'Add New Subject',
      addSubject: 'Add Subject',
      saveSubject: 'Save Subject',
      updateSubject: 'Update Subject',
    },
    modal: {
      addTitle: 'Add New Subject',
      editTitle: 'Edit Subject',
    },
    form: {
      labels: {
        subjectName: 'Subject Name',
        subjectCode: 'Subject Code',
        associatedGrades: 'Associated Grades',
      },
      hints: {
        selectGrades: 'Select one or more grades.',
      },
    },
    table: {
      loading: 'Loading subjects...',
      emptyTitle: 'No subjects found',
      emptyDescription: 'Try adjusting search or add a new subject.',
      columns: {
        subjectName: 'Subject Name',
        subjectCode: 'Subject Code',
        grades: 'Associated Grades',
      },
      actionTitles: {
        edit: 'Edit Subject',
        delete: 'Delete Subject',
      },
    },
  },

  cohorts: {
    searchPlaceholder: 'Search cohorts...',
    filters: {
      startAy: 'Start AY',
    },
    permissions: {
      noExport: 'You do not have permission to export/print cohorts',
    },
    confirms: {
      delete: 'Delete this cohort? This is only allowed if not in use.',
    },
    toasts: {
      created: 'Cohort created',
      updated: 'Cohort updated',
      deleted: 'Cohort deleted',
      archived: 'Archived',
      activated: 'Activated',
    },
    actions: {
      add: 'Add Cohort',
    },
    modal: {
      addTitle: 'Add Cohort',
      editTitle: 'Edit Cohort',
    },
    status: {
      archived: 'Archived',
    },
    form: {
      labels: {
        name: 'Name',
        startAcademicYear: 'Start Academic Year',
      },
      placeholders: {
        name: 'e.g. Dufcada 1aad',
        selectAcademicYear: 'Select Academic Year',
      },
    },
    table: {
      emptyTitle: 'No cohorts found',
      emptyDescription: 'Try adjusting filters or create a new cohort.',
      columns: {
        name: 'Name',
        startAy: 'AY (Start)',
      },
    },
  },

  promotions: {
    permissions: {
      noPreview: 'You do not have permission: Promotions Preview',
      noPromote: 'You do not have permission: Promotions Promote',
    },
    errors: {
      selectFiltersFirst: 'Select AY, Grade, Shift, Section, and Cohort first',
      selectAtLeastOneStudent: 'Select at least one student to preview',
      previewFailed: 'Preview failed',
      noScoresAllShort: 'All selected students have no exam scores.',
      runPreviewFirst: 'Run preview first',
      promotionFailed: 'Promotion failed',
      noScoresAllLong: 'All selected students have no exam scores. Please add/import scores first, then try Promote again.',
    },
    toasts: {
      completedBase: 'Promotion completed.',
      promotedCount: 'Promoted: {{count}}.',
      notEligibleCount: 'Not eligible (avg < 60): {{count}}.',
      graduatedCount: 'Graduated: {{count}}.',
      failedCount: 'Failed: {{count}}.',
    },
    roster: {
      title: 'Students',
      loading: 'Loading students...',
      emptyTitleNeedsFilters: 'Select filters to load students',
      emptyTitleNone: 'No students found',
      emptyDescriptionNeedsFilters: 'Select AY, Grade, Shift, Section and Cohort.',
      columns: {
        student: 'Student',
        current: 'Current',
      },
    },
    preview: {
      empty: 'Run Preview to see targets, auto-create needs, and graduations',
      columns: {
        student: 'Student',
        from: 'From',
        to: 'To',
        avg: 'Avg',
        failed: 'Failed',
      },
      summary: {
        total: 'Total',
        promotable: 'Promotable',
        graduates: 'Graduates',
        missingTargets: 'Missing Targets',
        capacityIssues: 'Capacity Issues',
      },
      status: {
        graduate: 'Graduate',
        notEligible: 'Not eligible (avg < 60)',
        missingGs: 'Missing GS (will be auto-created on promote)',
      },
    },
    timing: {
      label: 'Timing',
      placeholder: 'Timing',
      midYear: 'Mid-Year',
      yearEnd: 'Year-End',
    },
  },

  transfers: {
    searchPlaceholder: 'Search by name or ID',
    permissions: {
      noTransfer: 'You do not have permission to transfer students',
      noReturn: 'You do not have permission to return transfers',
    },
    errors: {
      failedToOpen: 'Failed to open transfer',
      selectAllFields: 'Please select Year, Grade, Shift and Section',
      failedToTransferWithStatus: 'Failed to transfer (status {{status}})',
      failedToReturnWithStatus: 'Failed to return (status {{status}})',
    },
    toasts: {
      noChanges: 'No changes: already in this section',
      transferred: 'Enrollment transferred',
      returned: 'Returned to previous',
    },
    labels: {
      previousSection: 'Previous section',
      studentFallback: 'Student',
      from: 'From',
    },
    actions: {
      transferSectionTitle: 'Transfer Section',
      opening: 'Opening…',
      returnTitle: 'Return',
      return: 'Return',
      transferring: 'Transferring…',
      confirmTransfer: 'Confirm Transfer',
    },
    recent: {
      title: 'Recent transfers (session)',
      note: 'Recent transfers are kept only during this page session.',
    },
    logs: {
      title: 'All Transfers',
      searchPlaceholder: 'Search by name or ID...',
      loading: 'Loading transfers...',
      emptyTitle: 'No transfers found',
      emptyDescription: 'Transfers will appear here when recorded.',
      columns: {
        date: 'Date',
        student: 'Student',
        from: 'From',
        to: 'To',
        type: 'Type',
        reason: 'Reason',
      },
      type: {
        revert: 'Revert',
        transfer: 'Transfer',
      },
    },
    candidates: {
      loading: 'Loading candidates...',
      emptyTitleNone: 'No candidates found',
      emptyTitleNeedsFilters: 'Select filters to begin',
      emptyDescriptionNone: 'Try adjusting filters or search keyword.',
      emptyDescriptionNeedsFilters: 'Choose Academic Year, Grade or Shift to load candidates.',
      columns: {
        studentId: 'Student ID',
        fullName: 'Full Name',
      },
    },
    modal: {
      title: 'Transfer Section',
      titleWithName: 'Transfer Section: {{name}}',
      loadingEnrollment: 'Loading current enrollment…',
      placeholders: {
        selectAcademicYear: '-- Select Academic Year --',
        selectGrade: '-- Select Grade --',
        selectShift: '-- Select Shift --',
      },
      notes: {
        forwardRules: 'Forward allowed to any future AY. Returns must match previous section.',
        noScoresMigrate: 'No scores migrate across AY.',
      },
    },
  },

  students: {
    common: {
      studentFallback: 'Student',
    },

    dashboard: {
      title: 'Student Dashboard',
      loadingStudent: 'Loading student…',
      moreTabs: 'More tabs',
    },

    attendance: {
      status: {
        notMarked: 'Not marked',
        present: 'Present',
        absent: 'Absent',
        late: 'Late',
        excused: 'Excused',
        other: 'Other',
      },
    },

    attendanceTab: {
      subtitle: 'Your daily attendance, grouped by date.',
      loading: 'Loading attendance…',
      empty: 'No attendance records yet.',
      allDay: 'All day',
      allDaySubtitle: 'No timetable match for this date.',
      lessonFallback: 'Lesson',
      loadFailed: 'Failed to load attendance',
    },

    enrollmentsTab: {
      loading: 'Loading enrollments…',
      loadFailed: 'Failed to load enrollments',
      emptyTitle: 'No enrollment history',
      emptyDescription: 'This student has no enrollment records yet.',
      columns: {
        joined: 'Joined',
        left: 'Left',
        sequence: 'Seq',
      },
    },

    transferTimeline: {
      empty: 'No transfers.',
      transferred: 'Transferred',
      returned: 'Returned',
    },

    timetableTab: {
      subtitle: 'Weekly timetable for the current enrollment.',
      loading: 'Loading timetable…',
      loadFailed: 'Failed to load timetable',
      noActiveClass: 'No active class right now.',
      todayLabel: 'Today:',
      todaySubtitle: 'Your schedule for today.',
      noClassesToday: 'No classes today.',
      empty: 'No timetable data.',
      teachersAndSubjects: 'Teachers & Subjects',
      noTeachers: 'No teachers',
      table: {
        day: 'Day',
        noPeriods: 'No periods',
        teacher: 'Teacher',
        subjects: 'Subjects',
      },
    },

    transcriptTab: {
      subtitle: 'Exam results and overall performance summary.',
      enrollmentsLoadFailed: 'Failed to load enrollments',
      noEnrollments: 'No enrollments found.',
      overallSummary: 'Overall Summary',
      rankTooltip: 'Overall rank across all levels and years.',
      labels: {
        overall: 'Overall',
        average: 'Average',
        rank: 'Rank',
      },
      loadingTranscript: 'Loading transcript…',
      noExams: 'No exams found.',
      examFallback: 'Exam',
      moreLevelsTooltip: 'More levels',
      levelFallback: 'Level',
      table: {
        subject: 'Subject',
        total: 'Total',
      },
    },

    libraryTab: {
      placeholder: 'Library content will appear here.',
    },

    transfersTab: {
      loadFailed: 'Failed to load transfers',
      emptyTitle: 'No transfers',
      emptyDescription: 'This student has no transfer records yet.',
    },

    profileTab: {
      loadFailed: 'Failed to load profile',
      personal: {
        title: 'Personal',
        subtitle: 'Student details',
      },
      academic: {
        title: 'Academic',
        subtitle: 'Latest enrollment information',
      },
      password: {
        title: 'Change Password',
        subtitle: 'Update your password',
        current: 'Current password',
        new: 'New password',
        confirm: 'Confirm password',
        fieldsRequired: 'Please fill in all required fields.',
        minLength: 'Password must be at least 6 characters.',
        noMatch: 'Passwords do not match.',
        changedSuccess: 'Password changed successfully.',
        changeFailed: 'Failed to change password.',
        defaultPasswordPlaceholder: 'Default password',
        defaultPasswordNote: 'Your account is using the default password. Please change it now.',
        showPasswordTitle: 'Show password',
        showCurrentAria: 'Show current password',
        showNewAria: 'Show new password',
        showConfirmAria: 'Show confirm password',
      },
    },

    selfDashboard: {
      welcome: 'Welcome, {{name}}',
      chooseBelow: 'Choose an option below',
      todayScheduleTitle: "Today's schedule",
      cards: {
        transcriptDesc: 'View exams and performance',
        attendanceDesc: 'View your attendance records',
        timetableDesc: 'View your weekly schedule',
        libraryDesc: 'Browse library content',
        profileDesc: 'View your profile',
      },
      attendance: {
        overview: 'Recorded attendance overview',
      },
      timetable: {
        classesPerDay: 'Classes per day',
      },
      transcript: {
        subtitle: 'Your performance overview',
        avgByLevel: 'Average by level',
        notEnoughData: 'Not enough data yet.',
        levelsDistribution: 'Levels distribution',
        levelsDistributionNote: 'Distribution across levels for the selected period.',
      },
    },

    searchPlaceholder: 'Search by name or ID...',
    addNew: 'Add New Student',
    add: 'Add Student',
    editTitle: 'Edit Student',
    addTitle: 'Add New Student',
    loadingFullDetails: 'Loading full details...',
    resetFilters: 'Reset filters',
    cohortOptional: 'Cohort (optional)',

    enrollmentStatus: {
      open: 'Open',
      active: 'Active',
      inactive: 'Inactive',
      promoted: 'Promoted',
      graduated: 'Graduated',
      transferred: 'Transferred',
      withdrawn: 'Withdrawn',
      all: 'All',
    },

    filters: {
      academicYear: 'Academic Year',
      grade: 'Grade',
      shift: 'Shift',
      section: 'Section',
      status: 'Status',
      all: 'All',
      active: 'Active',
      inactive: 'Inactive',
      searchAcademicYears: 'Search academic years…',
      searchSections: 'Type to search sections…',
    },

    table: {
      loading: 'Loading students...',
      emptyTitle: 'No students found',
      emptyDescription: 'Try adjusting filters or add a new student.',
      emptyAction: 'Add Student',
      columns: {
        studentId: 'Student ID',
        fullName: 'Full Name',
        gender: 'Gender',
        grade: 'Grade',
        section: 'Section',
        academicYear: 'Academic Year',
        shift: 'Shift',
        status: 'Status',
        contact: 'Contact',
        actions: 'Actions',
      },
      actionTitles: {
        viewProfile: 'View Profile',
        editStudent: 'Edit Student',
        deactivateStudent: 'Deactivate Student',
        reactivateStudent: 'Reactivate Student',
        resetPasswordDefault: 'Reset password to default (clears 24h lock/cooldown)',
      },
      actions: {
        resetPassword: 'Reset Password',
        view: 'View',
        edit: 'Edit',
        deactivate: 'Deactivate',
        reactivate: 'Reactivate',
      },
      confirms: {
        resetPassword: "Reset this student's password to the default password and clear the 24h lock/cooldown?",
        deactivate: 'Are you sure you want to deactivate this student?',
      },
      toasts: {
        updated: 'Student updated',
        created: 'Student created',
        deactivated: 'Student deactivated',
        reactivated: 'Student reactivated',
        passwordReset: 'Password reset to default. Student must change it after login.',
      },
      errors: {
        conflictUpdate: 'Conflict updating student',
        conflictCreate: 'Conflict creating student',
        resetFailed: 'Failed to reset password',
        updateFailed: 'Update failed',
        createFailed: 'Error creating student',
        network: 'Network error',
        loadDetailsFailed: 'Failed to load full student details',
        loadDetailsError: 'Error loading student details',
      },
      permissions: {
        noAdd: 'You do not have permission to add students',
        noEdit: 'You do not have permission to edit students',
        noExport: 'You do not have permission to export/print students',
      },
    },

    export: {
      filename: 'students.pdf',
      sheetName: 'Students',
      sectionPrefix: 'Sec',
      labels: {
        academicYear: 'Academic Year',
        grade: 'Grade',
        shift: 'Shift',
        section: 'Section',
        status: 'Status',
        cohort: 'Cohort',
      },
      selected: 'selected',
    },

    form: {
      fullName: 'Full Name',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      dob: 'Date of Birth',
      guardianName: 'Parent/Guardian Name',
      contactNumber: 'Contact Number',
      admissionDate: 'Admission Date',
      address: 'Address',
      academicYear: 'Academic Year',
      cohort: 'Cohort',
      grade: 'Grade',
      shift: 'Shift',
      enrollSection: 'Enroll in Section',
      selectAcademicYear: '-- Select Academic Year --',
      selectCohort: '-- Select Cohort --',
      selectGrade: '-- Select Grade --',
      selectShift: '-- Select Shift --',
      selectSection: '-- Select Section --',
      loadingSections: 'Loading sections…',
      cancel: 'Cancel',
      saveStudent: 'Save Student',
      updateStudent: 'Update Student',
      saving: 'Saving…',
      updating: 'Updating…',
      validations: {
        academicYearRequired: 'Academic Year is required',
        cohortRequired: 'Cohort is required',
        gradeRequired: 'Grade is required',
        shiftRequired: 'Shift is required',
        sectionRequired: 'Section is required',
      },
      info: {
        noSections: 'No sections found. Adjust filters.',
      },
    },
  },

  teachers: {
    searchPlaceholder: 'Search teachers...',
    addNew: 'Add New Teacher',
    addTitle: 'Add Teacher',
    editTitle: 'Edit Teacher',
    resetFilters: 'Reset filters',

    profile: {
      backToTeachers: 'Back to Teachers',
      role: 'Role',
      loading: 'Loading teacher profile…',
      loadFailed: 'Failed to load teacher profile',
      audit: {
        title: 'Audit History',
        subtitle: 'Recent actions recorded for this teacher account',
        loadFailed: 'Failed to load audit history',
        emptyTitle: 'No audit history.',
        emptyDescription: 'No actions have been recorded yet.',
      },
    },

    dashboard: {
      home: {
        welcome: 'Welcome',
        welcomeWithName: 'Welcome, {{name}}',
        summaryLine: 'Choose what you want to do below.',
        cards: {
          myClasses: {
            title: 'My Classes',
            description: 'View your assigned classes and active rosters',
          },
          timetable: {
            title: 'Timetable',
            description: 'See your schedule and class timetables',
          },
          attendance: {
            title: 'Attendance',
            description: 'Mark and review attendance for your classes',
          },
          attendanceReports: {
            title: 'Attendance Reports',
            description: 'Summary reports by date range',
          },
          exam: {
            title: 'Exam',
            description: 'Enter scores and review results',
          },
          profile: {
            title: 'Profile',
            description: 'Account details and change password',
          },
          announcements: {
            title: 'Announcements',
            description: 'School announcements and updates',
          },
        },
      },

      common: {
        filters: 'Filters',
        sectionPrefix: 'Sec',
        section: 'Section',
        subject: 'Subject',
        selectSection: 'Select section',
        selectSubject: 'Select subject',
        selectSectionFirst: 'Select section first',
        downloadFailed: 'Download failed. Please try again.',
        liveTeacherScoped: 'Live data (teacher-scoped)',
        downloadPng: 'PNG',
        downloadPdf: 'PDF',
        teachersOnly: 'This card is available for teachers only.',
        noTeacherRef: 'No teacherRef found on your account.',
        kpis: 'KPIs',
      },

      profile: {
        title: 'My Profile',
        subtitle: 'Quick account info',
        teacherFallback: 'Teacher',
        roleFallback: 'TEACHER',
        fields: {
          username: 'Username',
          teacherRef: 'Teacher Ref',
          email: 'Email',
          phone: 'Phone',
        },
        stats: {
          classes: 'Classes',
          subjects: 'Subjects',
          today: 'Today',
          week: 'Week',
        },
        tip: 'Tip: If profile fields are missing, ask admin to update your teacher record.',
      },

      classes: {
        sectionPrefix: 'Sec',
        classFallback: 'Class',
        countFailed: 'Failed',
        rosterLoadFailed: 'Failed to load roster',
        title: 'My Classes',
        subtitle: 'View active students for your assigned classes.',
        loading: 'Loading classes…',
        loadFailed: 'Failed to load classes',
        empty: 'No assigned classes.',
        checkingStudents: 'Checking students…',
        studentsUnavailable: 'Students unavailable',
        activeStudentsCount: '{{count}} active students',
        noActiveStudents: 'No active students',
        tapToViewStudents: 'Tap to view students',
        studentsCardTitle: 'Students',
        viewStudents: 'View Students',
        activeRoster: 'Active Roster',
        loadingRoster: 'Loading roster…',
        noActiveStudentsFound: 'No active students found.',
        rosterTable: {
          studentId: 'Student ID',
          fullName: 'Full Name',
          gender: 'Gender',
        },
      },

      timetable: {
        sectionPrefix: 'Sec',
        fetchingToday: "Fetching today’s schedule…",
        missingTeacherRef: 'Teacher account is missing teacherRef.',
        noClassesToday: 'No classes scheduled for today.',
        classFallback: 'Class',
        todayTitle: "Today's Schedule",
        assignedClassesTitle: 'My Assigned Classes',
        sectionFallback: 'Section',
        table: {
          day: 'Day',
        },
        loadingSlots: 'Loading slots…',
        selectClass: 'Select a class to view timetable.',
        noSlotsForClass: 'No timetable slots found for this class.',
      },

      attendance: {
        title: 'Attendance',
        assignmentsLoadFailed: 'Failed to load teacher assignments.',
        reportLoadFailed: 'Failed to load attendance report.',
        status: {
          present: 'Present',
          absent: 'Absent',
          late: 'Late',
          excused: 'Excused',
          sick: 'Sick',
          medical: 'Medical',
          family: 'Family',
          other: 'Other',
        },
        views: {
          statusTrend: 'Status trend',
          byPeriods: 'By periods',
          performance: 'Performance',
        },
        maxRange: 'Max range: 31 days',
        range: {
          title: 'Range',
          today: 'Today',
          last7: 'Last 7',
          custom: 'Custom',
        },
        dates: 'Dates',
        loadingTimetablePeriods: 'Loading timetable periods…',
        noPeriodsForSubject: 'No timetable periods for this subject.',
        kpis: {
          allDayPct: 'All-day%',
          perPeriodPct: 'Per-period%',
          roster: 'Roster',
          attendancePct: 'Attendance %',
        },
        loading: 'Loading attendance…',
        selectFilters: 'Select Section + Subject + date range to view charts.',
        noData: 'No attendance data found for the selected filters.',
        performance: {
          title: 'Attendance performance',
          subtitle: 'Percent breakdown (prefers ALL DAY per date)',
          markedDays: 'Marked days',
          markedDaysNote: 'One row per date (DAY else PERIOD)',
          rosterNote: 'From report meta',
          statusPercentages: 'Status percentages',
          totalRecords: 'Total records: {{count}}',
        },
        statusTrend: {
          title: 'Attendance status trend',
          subtitle: 'All-day (DAY) and Per-period (LESSON)',
          dailyTrend: 'Daily trend',
          dailyTrendNote: 'One line per date (prefers ALL DAY)',
          noTrendRows: 'No trend rows found.',
          noTimetablePeriodsNote: 'Note: no timetable periods found for this subject; PERIOD rows may be missing.',
        },
        badges: {
          allDay: 'ALL DAY',
          period: 'PERIOD',
        },
        byPeriod: {
          title: 'Attendance by period',
          subtitle: 'Present total',
          empty: 'No lesson periods found in this range.',
        },
        source: 'Source: Attendance Reports summary (teacher-scoped)',
      },

      results: {
        title: 'Results',
        assignmentsLoadFailed: 'Failed to load teacher assignments.',
        summaryLoadFailed: 'Failed to load summary',
        performanceLoadFailed: 'Failed to load performance.',
        examFallback: 'Exam',
        examType: 'Exam Type',
        views: {
          distribution: 'Distribution',
          topStudents: 'Top students',
          performance: 'Performance',
        },
        modesNote: 'Teacher modes: Subject / Exam Type',
        filters: {
          academicYear: 'Academic Year',
          selectYear: 'Select year',
          mode: 'Mode',
          selectYearFirst: 'Select year first',
          selectExamType: 'Select exam type',
        },
        kpis: {
          classAvg: 'Class Avg',
          passPct: 'Pass %',
          topBottom: 'Top/Bottom',
        },
        loadingPerformance: 'Loading performance…',
        loading: 'Loading results…',
        selectFilters: 'Select Academic Year + Section + (Subject/Exam Type) to view charts.',
        noPerformanceData: 'No performance data found for the selected filters.',
        noMarks: 'No exam marks found for the selected filters.',
        performance: {
          title: 'Exam type performance',
          subjectMode: 'Subject',
          overallMode: 'Overall',
          template: 'Template',
          help: 'Vertical bars = exam types • Left axis = percentage (avg / maxScore)',
          avg: 'Avg',
          tip: 'Tip: switch Mode=Subject to see performance for a single subject; otherwise it uses Overall.',
        },
        distribution: {
          title: 'Score distribution',
          subtitle: 'Students per range',
          kpiIdea: 'KPI idea:',
        },
        top: {
          title: 'Top students',
          subtitle: 'By average',
          studentFallback: 'Student',
        },
        studentFallback: 'Student',
        source: 'Source: Exams summary (teacher-scoped)',
        modesFooter: 'Modes:',
      },
    },

    filters: {
      status: 'Status',
      all: 'All',
      active: 'Active',
      inactive: 'Inactive',
    },

    sort: {
      name: 'Name',
      id: 'ID',
      created: 'Created',
    },

    table: {
      loading: 'Loading teachers...',
      emptyTitle: 'No teachers.',
      emptyDescription: 'Try adjusting search or add a new teacher.',
      columns: {
        name: 'Name',
        teacherId: 'Teacher ID',
        email: 'Email',
        phone: 'Phone',
        salary: 'Salary',
        createdAt: 'Created',
        status: 'Status',
        actions: 'Actions',
      },
      actions: {
        view: 'View',
        edit: 'Edit',
        assignments: 'Assignments',
        resetPassword: 'Reset Password',
        deactivate: 'Deactivate',
        reactivate: 'Reactivate',
      },
      actionTitles: {
        viewProfile: 'View teacher profile & audit history',
        editTeacher: 'Edit Teacher',
        deactivateTeacher: 'Deactivate Teacher',
        reactivateTeacher: 'Reactivate Teacher',
        resetPasswordDefault: 'Reset password to default (clears 24h lock/cooldown)',
      },
      confirms: {
        toggle: '{{verb}} this teacher?',
        resetPassword: "Reset this teacher's password to the default password and clear the 24h lock/cooldown?",
      },
      toasts: {
        created: 'Teacher created',
        updated: 'Teacher updated',
        deactivated: 'Teacher deactivated',
        reactivated: 'Teacher reactivated',
        passwordReset: 'Password reset to default. Teacher must change it after login.',
      },
      errors: {
        saveFailed: 'Save failed',
        updateFailed: 'Update failed',
        resetFailed: 'Reset failed',
        loadFailed: 'Failed to load teachers',
      },
      permissions: {
        noAdd: 'You do not have permission to add teachers',
        noEdit: 'You do not have permission to edit teachers',
        noAssign: 'You do not have permission to assign teachers',
        noDeactivate: 'You do not have permission to deactivate teachers',
        noReactivate: 'You do not have permission to reactivate teachers',
        noResetPw: 'You do not have permission to reset passwords',
        noExport: 'You do not have permission to export/print teachers',
      },
    },

    export: {
      filename: 'teachers.pdf',
      sheetName: 'Teachers',
      labels: {
        search: 'Search',
        status: 'Status',
      },
    },

    form: {
      fullName: 'Full Name',
      teacherId: 'Username (Teacher ID)',
      teacherIdPlaceholder: 'e.g. ID01',
      teacherIdHelp: 'Teacher can login using this username or their email.',
      email: 'Email',
      phone: 'Phone',
      salary: 'Salary',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      cancel: 'Cancel',
      save: 'Save',
      update: 'Update',
      saving: 'Saving…',
      updating: 'Updating…',
    },

    assignments: {
      title: 'Assignments • {{name}}',
      loading: 'Loading assignments...',
      errorLoadAssignments: 'Failed to load assignments',
      errorLoadSectionsSubjects: 'Failed to load sections/subjects',
      errorLoadData: 'Failed to load data',
      selectLevel: 'Select level…',
      selectShift: 'Select shift…',
      selectSection: 'Select section…',
      selectSubject: 'Select subject…',
      add: 'Add Assignment',
      added: 'Assignment added',
      addFailed: 'Failed to add assignment',
      removeFailed: 'Failed to remove assignment',
      confirmRemove: 'Remove this assignment?',
      none: 'No assignments.',
      columns: {
        level: 'Level',
        shift: 'Shift',
        section: 'Section',
        subject: 'Subject',
      },
      remove: 'Remove',
    },
  },

  users: {
    searchPlaceholder: 'Search by name or username...',
    addUser: 'Add User',
    editTitle: 'Edit User',
    createTitle: 'Create User',
    resetFilters: 'Reset',

    filters: {
      role: 'Role',
      status: 'Status',
      allRoles: 'All Roles',
      allStatus: 'All Status',
      admin: 'Admin',
      staff: 'Staff',
      active: 'Active',
      inactive: 'Inactive',
    },

    table: {
      loading: 'Loading users...',
      emptyTitle: 'No users found',
      emptyDescription: 'Try adjusting filters or add a new user.',
      columns: {
        fullName: 'Full Name',
        username: 'Username',
        email: 'Email',
        phone: 'Phone',
        salary: 'Salary',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
      },
      actions: {
        view: 'View',
        edit: 'Edit',
        deactivate: 'Deactivate',
        activate: 'Activate',
        unlock: 'Unlock',
      },
      actionTitles: {
        view: 'View user',
        edit: 'Edit user',
        deactivate: 'Deactivate user',
        activate: 'Activate user',
        unlock: 'Unlock login (clear lockout)',
      },
    },

    export: {
      filename: 'users.pdf',
      sheetName: 'Users',
      labels: {
        search: 'Search',
        role: 'Role',
        status: 'Status',
      },
    },

    form: {
      fields: {
        fullName: 'Full Name',
        username: 'Username',
        email: 'Email',
        phone: 'Phone',
        salary: 'Salary',
        password: 'Password',
        confirmPassword: 'Confirm Password',
      },
      newPasswordOptional: 'New Password (optional)',
      loadingDetails: 'Loading user details...',
      passwordsNoMatch: 'Passwords do not match',
      role: 'Role',
      staff: 'Staff',
      admin: 'Admin',
      selectModule: 'Select Module',
      chooseModule: '-- Choose Module --',
      permissionsFor: 'Permissions for {{module}}',
      save: 'Save',
      update: 'Update',
      saving: 'Saving...',
      updating: 'Updating...',
      validations: {
        passwordRequiredNew: 'Password is required for new users',
        passwordMin: 'Password must be at least 6 characters',
      },
    },

    profile: {
      failedLoad: 'Failed to load profile',
      loadingDetails: 'Loading user details…',
      couldNotLoad: 'Could not load user profile.',
      backToUsers: 'Back to Users',
      rolePrefix: 'Role: {{role}}',
      labels: {
        fullName: 'Full Name',
        username: 'Username',
        email: 'Email',
        phone: 'Phone',
        role: 'Role',
        status: 'Status',
        createdAt: 'Created At',
        lastLogin: 'Last Login',
      },
      never: 'Never',
      auditHistory: 'Audit History',
      auditLoadFailed: 'Failed to load audit history',
      auditEmptyTitle: 'No audit history.',
      auditEmptyDescription: 'This user has no recorded actions yet.',
    },

    toasts: {
      created: 'User created successfully',
      updated: 'User updated successfully',
      saveFailed: 'Failed to save user',
      statusUpdated: 'Status updated',
      statusUpdateFailed: 'Failed to update status',
      lockoutReset: 'Login lockout reset successfully',
      lockoutResetFailed: 'Failed to reset lockout',
      updatedElsewhere: 'This user was updated in another tab. Close/reopen to sync.',
      loadDetailsFailed: 'Failed to load user details',
      uniqueExists: 'Username, Email, or Phone already exists',
      phoneDigitsOnly: 'Phone must contain digits only',
      phoneMaxDigits: 'Phone number cannot exceed 9 digits',
    },

    confirms: {
      toggleStatus: '{{verb}} this user?',
      resetLockout: 'Reset login lockout for this user?',
    },
  },

  exams: {
    settings: {
      actions: {
        saveTotal: 'Save Total',
        cloneToNewTemplate: 'Clone to New Template',
        setAsDefault: 'Set as Default',
        deleteTemplate: 'Delete Template',
      },
      states: {
        loadingTemplate: 'Loading template…',
        refreshing: 'Refreshing…',
      },
      hints: {
        selectTemplateToEdit: 'Select a template to edit.',
        mustMatchToActivate: '(Must match to activate)',
        templateLockedHelp: 'This template already has saved scores and is locked. You cannot edit total or columns. You may delete columns that have no scores, or use “Clone to New Template”.',
      },
      labels: {
        declaredTotal: 'Declared Total',
        templateWithVersion: 'Template',
        defaultBadge: 'Default',
        defaultSuffix: ' (default)',
        sumMax: 'Sum Max',
        total: 'Total',
        hasScores: 'Has scores',
      },
      placeholders: {
        template: 'Template',
        newColumnName: 'New column name',
        max: 'Max',
      },
      table: {
        emptyTitle: 'No components.',
        emptyDescription: 'Add a component to this template.',
        columns: {
          name: 'Name',
          maxScore: 'Max Score',
        },
      },
      confirms: {
        deleteColumn: 'Delete this column? This cannot be undone.',
        deleteTemplateVersion: 'Delete template v{{version}}? This cannot be undone.',
      },
      toasts: {
        clonedToVersion: 'Cloned to v{{version}}',
        defaultTemplateUpdated: 'Default template updated',
        deleted: 'Deleted',
        deletedTemplateVersion: 'Deleted template v{{version}}',
      },
      errors: {
        loadTemplateVersionsFailed: 'Failed to load template versions',
        loadTemplateFailed: 'Failed to load template',
        noPermissionEditTemplates: 'You do not have permission to edit exam templates',
        templateLockedTotal: 'This template already has scores and is locked. Total cannot be edited.',
        templateLockedColumns: 'This template already has scores and is locked. Columns cannot be edited.',
        totalMustBeGt0: 'Total must be > 0',
        saveTotalFailed: 'Failed to save total',
        cloneFailed: 'Clone failed',
        activateFailed: 'Activate failed',
        nameRequired: 'Name is required',
        maxScoreMustBeGt0: 'Max score must be > 0',
        orderMustBeGt0: 'Order must be > 0',
        sumMaxCannotExceedTotal: 'Sum of max scores cannot exceed the declared total',
        maxScoreExceedsTotal: 'Max score exceeds declared total',
        orderMustBeUnique: 'Order must be unique',
        saveFailed: 'Save failed',
        addFailed: 'Add failed',
        deleteFailed: 'Delete failed',
        deleteTemplateFailed: 'Delete template failed',
        templateHasScoresCloneToAdd: 'This template already has scores. Clone a new template to add columns.',
        cannotDeleteColumnHasScores: 'Cannot delete: this column has saved scores',
        cannotDeleteDefaultTemplate: 'Cannot delete the default (active) template',
        cannotDeleteTemplateHasScores: 'Cannot delete: this template has saved scores',
      },
    },

    management: {
      timeline: {
        title: 'Cohort timeline',
        noData: 'No timeline data found for this cohort.',
        itemFallback: 'Timeline item',
      },

      searchPlaceholders: {
        templates: 'Search templates…',
      },

      emptyStates: {
        selectFilters: 'Select Academic Year, Grade, Shift and Section.',
        chooseSubject: 'Choose a Subject to load the grid.',
        loadingGrid: 'Loading grid…',
        noStudents: 'No students or data for this selection.',
      },

      locked: {
        teacherHelp: 'Some students are locked because they already have scores saved under another template.',
        adminHelp: 'Some students are locked because they already have scores under another template. Use the Template dropdown above to switch to the version shown in the error.',
        title: 'Locked',
        titleWithVersions: 'Locked ({{versions}})',
      },

      table: {
        student: 'Student',
        totalWithMax: 'Total ({{totalMax}})',
      },

      cell: {
        maxTitle: 'Max: {{max}}',
        saveFailed: 'Save failed',
        saved: 'Saved',
      },

      actions: {
        saveAllTitle: 'Save all pending entries',
      },

      toasts: {
        savedScoresSuccessfully: 'Saved scores successfully',
        updatedScoresSuccessfully: 'Updated scores successfully',
      },

      errors: {
        loadSectionSubjectsFailed: 'Failed to load section subjects',
        noPermissionInputScores: 'You do not have permission to input exam scores',
        anotherTemplate: 'another template',
        lockedStudent: 'This student already has scores saved under {{version}}. Switch to that template to edit.',
        saveFailed: 'Save failed',
        fixInvalidEntries: 'Fix {{count}} invalid entries before saving.',
        loadGridFailed: 'Failed to load grid',
        lockedCount: '{{count}} student(s) already have scores saved under another template (locked).',
      },
    },
  },

  results: {
    page: {
      errors: {
        loadSubjectsFailed: 'Failed to load subjects',
        loadSummaryFailed: 'Failed to load summary',
        noPermissionPrint: 'You do not have permission to print results',
      },

      toasts: {
        noMarksForSelection: 'No exam marks found for the selected class and filters.',
      },

      export: {
        enrollment: 'Enrollment',
        sheetName: 'Results',
        title: 'Results & Rankings',
      },

      filters: {
        mode: 'Mode',
        examType: 'Exam Type',
        nLabel: 'N',
      },

      searchPlaceholders: {
        examTypes: 'Search exam types…',
      },

      timeline: {
        title: 'Cohort Timeline:',
      },

      emptyStates: {
        selectFilters: 'Select Academic Year, Grade, Shift, and Section to view results.',
        chooseSubject: 'Choose a Subject to view results.',
        chooseExamType: 'Choose an Exam Type to view results.',
        noResults: 'No results found for the selected filters.',
      },

      modes: {
        subject: 'Subject',
        overall: 'Overall',
        examType: 'Exam Type',
        top: 'Top N',
        bottom: 'Bottom N',
        trend: 'Trend (Mid vs Final)',
        difficulty: 'Subject Difficulty',
      },

      table: {
        rank: 'Rank',
        student: 'Student',
        totalWithMax: 'Total ({{max}})',
        average: 'Average',
        midTerm: 'Mid-term',
        final: 'Final',
        delta: 'Delta',
        classAvgDelta: 'Class Avg Delta',
        avg: 'Avg',
        students: 'Students',
        classAvgSubjects: 'Class Avg (subjects)',
        classAverage: 'Class Average',
      },
    },
  },

  transcript: {
    page: {
      errors: {
        loadLookupsFailed: 'Failed to load lookups',
        noPermissionPrint: 'You do not have permission to print transcript',
      },

      toasts: {
        gradeNoTranscript: 'Grade {{grade}} has no transcript.',
        nothingToExportYet: 'Nothing to export yet. Load transcript first.',
      },

      export: {
        sheetName: 'Transcript',
      },

      states: {
        loadingLastTranscript: 'Loading last transcript…',
        loadingTranscriptsLevels: 'Loading transcripts (levels)…',
        loadingFullTranscript: 'Loading full transcript…',
      },

      timeline: {
        title: 'Cohort Timeline',
        noData: 'No timeline data.',
        itemFallback: 'Timeline item',
      },

      studentPicker: {
        searchLabel: 'Search Student',
        openClassListTitle: 'Open class list',
        selectFromClass: 'Select from class',
        filterListPlaceholder: 'Filter list…',
        noStudentsFound: 'No students found.',
        selectStudentAria: 'Select {{name}}',
        removeStudentAria: 'Remove {{name}}',
      },

      modes: {
        full: 'Full',
        latest: 'Latest',
        levels: 'Levels',
      },

      levels: {
        levelsButton: 'Levels',
        selectTitle: 'Select Levels',
        noGrades: 'No grades.',
      },

      labels: {
        studentId: 'Student ID',
      },

      emptyStates: {
        noTranscriptData: 'No transcript data for the selected mode/filters.',
        noTranscriptRows: 'No transcript rows',
        selectGrades: 'Select one or more grades to view transcripts.',
      },

      table: {
        total: 'Total',
        overall: 'Overall',
      },
    },
  },

  dashboard: {
    cards: {
      scoreActivity: {
        title: 'Scores Activity',
        subtitle: 'Mark entry edits (tabbed)',
        stats: {
          touched: 'Touched',
          created: 'Created',
          updated: 'Updated',
        },
        noteDefinition: '“{{label}}” = scores whose latest edit happened in that bucket.',
      },

      announcementsMix: {
        title: 'Announcements Mix',
        subtitle: 'Created vs updated (tabbed)',
        labels: {
          allCreated: 'All (created)',
        },
        legend: {
          created: 'Created',
          updated: 'Updated',
        },
        roles: {
          all: 'All',
          students: 'Students',
          teachers: 'Teachers',
          staff: 'Staff',
          admin: 'Admin',
          unknown: 'Unknown',
        },
        empty: 'No announcements in this range.',
      },

      attendance: {
        subtitle: 'Admin/Staff overview (all classes)',
        kpis: {
          presentPct: 'Present%',
          days: 'Days',
        },
        labels: {
          allDay: 'All-day',
          perPeriod: 'Per-period',
        },
        notes: {
          oneRowPerDate: 'One row per date (prefers ALL DAY when available)',
          pickAnyRange: 'Pick any date range.',
          showsRecords: 'Shows attendance records in the selected range.',
        },
        export: {
          title: 'Attendance dashboard export',
        },
        errors: {
          loadFailed: 'Failed to load attendance summary.',
        },
        performance: {
          subtitle: 'Percent breakdown',
          totalRecordsTitle: 'Total records',
          totalRecordsNote: 'Sum of all statuses',
        },
        byPeriod: {
          subtitle: 'Aggregated over selected range',
          noLessonData: 'No per-period (lesson) data found in this range.',
          periodsTitle: 'Periods',
          excludesAllDay: 'Excludes ALL DAY',
        },
        statusTrend: {
          subtitle: 'Per day (all classes)',
          hoverNote: 'Hover segments for counts',
        },
        footer: {
          source: 'Source: Dashboard summary (admin/staff)',
          kpisLine: 'KPIs: Present% • Days',
        },
      },

      results: {
        subtitle: 'Admin/Staff overview (selected class)',
        export: {
          title: 'Results dashboard export',
        },
        onlyAdminStaff: 'This card is available for admin/staff only.',
        selectFilters: 'Select Academic Year + Section to view charts. (Subject/Exam Type filters are optional.)',
        footer: {
          source: 'Source: Exams summary (admin/staff scope)',
        },
        modes: {
          allSubjects: 'All Subjects',
          subject: 'Subject',
          examType: 'Exam Type',
        },
        labels: {
          subjectsInClass: 'Subjects in this class',
          showing: 'Showing',
          subject: 'Subject',
        },
        placeholders: {
          subjectOptional: 'Subject (optional)',
          selectSectionFirst: 'Select section first',
          selectYearFirst: 'Select year first',
        },
        notes: {
          modeTip: 'Tip: switch',
          modeTipTail: 'to filter by one subject, or keep',
        },
        errors: {
          loadClassSubjectsFailed: 'Failed to load class subjects.',
        },
        distribution: {
          kpiLine: 'KPI: Class Avg • Pass % • Top 10',
        },
      },
    },

    page: {
      welcome: 'Welcome',
      welcomeUser: 'Welcome, {{name}}',
      academicYearLabel: 'Academic Year: {{year}}',
      subtitle: 'Dashboard overview',
      errors: {
        loadFailed: 'Failed to load dashboard data.',
      },
      modules: {
        students: 'Students',
        teachers: 'Teachers',
        staff: 'Staff',
        classes: 'Classes',
        subjects: 'Subjects',
        cohorts: 'Cohorts',
        transfers: 'Transfers',
        announcements: 'Announcements',
        activeCount: 'Active: {{count}}',
        classesSubtitle: 'Grade sections',
        subjectsSubtitle: 'All subjects',
        cohortsSubtitle: 'All cohorts',
        inSelectedRange: 'In selected range',
      },
      newStudents: {
        title: 'New Students',
        subtitle: 'First-ever enrollment trend',
        yAxisLabel: 'Student count',
      },
    },
  },
};

export const resources = {
  en: { translation: en },
  ar: { translation: ar },
  so: { translation: so },
};

export const supportedLanguages = ['en', 'so', 'ar'];
export const defaultLanguage = 'en';
